Add controllers
ProfessorKauftman/java-shareit pull request #1
Opened 2024-04-15 13:53 UTC by ProfessorKauftman

Добавление новой логики в пакетах Item и User

2024-04-16 08:15 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-04-16 08:15 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                                  @PathVariable("itemId") Long itemId) {
Нет необходимости в `"itemId"`, так как оно совпадает с названием переменной

2024-04-16 08:15 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                                       @RequestParam(name = "text") String text) {
Аналогично, нет необходимости в поле `name`

2024-04-16 08:15 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceDaoImpl.java
> +    private final Map<Long, List<Item>> items = new HashMap<>();
У нас может быть список `Item`-ов принадлежащих одному идентификатору?
Выглядит слегка сомнительно :)

2024-04-16 08:15 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceDtoImpl.java
> +        if (itemOptional.isPresent()) {
Лучше использовать конструкцию `.map(),orElse()`

2024-04-16 08:15 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceDtoImpl.java
> +        return ItemMapper.itemToDto(getItem.get());
```java
return serviceDao.getItemById(itemId)
    .map(ItemMapper::itemToDto)
    .orElseThrow(() -> new NotFoundException(String.format("User with id %s"
                    + " doesn't have item with id %s", userId, itemId)));
```

2024-04-16 08:15 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@AllArgsConstructor
Аннотация `@RequiredArgsConstructor` уже есть внутри `@Data`

2024-04-16 08:15 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/service/UserServiceDaoImpl.java
> +        emails.remove(oldEmail);
Операции `remove` и `add` в `Set` хотя и занимают `O(1)` времени в данном случае являются необязательными и на них можно сэкономить:

```java
if (emails.contains(newEmail)) {
    throw new NotUniqueEmailException("User with this email already exists");
}
emails.remove(oldEmail);
emails.add(newEmail);
```

2024-04-16 08:15 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/service/UserServiceDaoImpl.java
> +    private void checkEmailExists(User user) {
Если бы мы передавали сюда строковый `email`, а не пользователя, то метод можно было бы использовать в методе ниже

2024-04-16 08:15 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/service/UserServiceDtoImpl.java
> +        }
Можно использовать тернарный оператор

2024-04-16 08:15 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/service/UserServiceDtoImpl.java
> +        boolean isEmailNotUnique = userServiceDao.findAllUsers().stream()
У нас же есть внутри коллекция `emails`, которая позволяет проверять есть ли в ней элемент за `O(1)`, почему бы не написать для ее метода `contains` обертку.

Также за `O(1)` можно найти пользователя в коллекции по идентификатору и сравнить их `email`. Суммарная сложность операции уменьшится с `O(n)` до `O(1)`

2024-04-16 12:20 UTC, ProfessorKauftman commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                                  @PathVariable("itemId") Long itemId) {
+

2024-04-16 12:20 UTC, ProfessorKauftman commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                                       @RequestParam(name = "text") String text) {
+

2024-04-16 12:20 UTC, ProfessorKauftman commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceDaoImpl.java
> +    private final Map<Long, List<Item>> items = new HashMap<>();
+

2024-04-16 14:09 UTC, ProfessorKauftman commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceDtoImpl.java
> +        if (itemOptional.isPresent()) {
+

2024-04-16 14:15 UTC, ProfessorKauftman commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@AllArgsConstructor
сделал, но когда убрал эту аннотацию, мне пришлось прописывать все значения при создании нового юзера
![image](https://github.com/ProfessorKauftman/java-shareit/assets/144950381/927d115c-1832-43aa-9058-ed26e070abb9)

2024-04-16 14:30 UTC, ProfessorKauftman commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceDtoImpl.java
> +        return ItemMapper.itemToDto(getItem.get());
исправлено

2024-04-16 17:07 UTC, ProfessorKauftman commented on src/main/java/ru/practicum/shareit/user/service/UserServiceDaoImpl.java
> +        emails.remove(oldEmail);
исправлено

2024-04-16 17:21 UTC, ProfessorKauftman commented on src/main/java/ru/practicum/shareit/user/service/UserServiceDtoImpl.java
> +        }
исправил

2024-04-18 06:28 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-04-19 14:25 UTC, merged